gerencia/urls.py
from django.urls import path
from .views import inicio_gerencia, listagem_noticia, cadastrar_noticia, editar_noticia, editar_categoria, remover_categoria, cadastrar_categoria

app_name = 'gerencia'

urlpatterns = [
    path('', inicio_gerencia, name='inicio_gerencia'),
    path('noticias/', listagem_noticia, name='listagem_noticia'),
    path('noticias/cadastro', cadastrar_noticia, name='cadastro_noticia'),
    path('noticias/editar/<int:id>', editar_noticia, name='editar_noticia'),
    path('categoria/editar/<int:id>/', editar_categoria, name='editar_categoria'),
    path('categoria/remover/<int:id>/', remover_categoria, name='remover_categoria'),
    path('categoria/cadastro/', cadastrar_categoria, name='cadastro_categoria')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from curso import views
from django.conf import settings
from django.conf.urls.static import static
from gerencia.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index' ), # index
    path('usuario/',include('usuarios.urls')),
    path('gerencia/',include('gerencia.urls')),
    path('curso/<int:curso_id>',views.detalhe_curso,name='detalhe_curso'),
    path('sobre/',views.pagina_sobre,name='pagina_sobre'),
    path('teste/',views.pagina_teste,name='pagina_teste'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gerencia/models.py
from django.db import models
from usuarios.models import UserBlog

class Categoria(models.Model):
    nome = models.CharField(max_length=100)
    
    def __str__(self):
        return self.nome

class Noticia(models.Model):
    titulo = models.CharField(max_length=100)
    data_publicacao = models.DateField(auto_created=True)
    texto = models.TextField()
    image = models.ImageField(upload_to='noticias/')
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    usuario = models.ForeignKey( UserBlog, on_delete=models.CASCADE, blank=True,null=True)  
    

    

gerencia/forms.py
from django import forms
from .models import Noticia

class NoticiaForm(forms.ModelForm):
    
    class Meta:
        model = Noticia
        fields = '__all__'
        widgets = {
            'data_publicacao': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}), 
            'texto': forms.Textarea(attrs={'class': 'form-control'}),  
            'titulo': forms.TextInput(attrs={'class': 'form-control'}), 
            'image': forms.FileInput(attrs={'class': 'form-control'}), 
            'categoria': forms.Select(attrs={'class': 'form-control'}),

        }



from django import forms
from .models import Categoria
from usuarios.models import UserBlog  # Importe o modelo de usuário personalizado

class NoticiaFilterForm(forms.Form):
    titulo = forms.CharField(
        max_length=200,
        required=False,
        label='Título',
        widget=forms.TextInput(attrs={'placeholder': 'Digite o título','class': 'form-control'})
    )
    data_publicacao_inicio = forms.DateField(
        required=False,
        label='Data de Publicação (Início)',
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    data_publicacao_fim = forms.DateField(
        required=False,
        label='Data de Publicação (Fim)',
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        required=False,
        label='Categoria',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nome']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
        }

gerencia/views.py
from django.shortcuts import render, redirect
from .forms import NoticiaForm, NoticiaFilterForm, CategoriaForm
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy
from django.core.paginator import Paginator

from .models import Noticia, Categoria

def login_required_message(view_func):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, 'Você precisa estar logado para acessar a página solicitada.')
            return redirect(reverse_lazy('usuarios:login'))
        return view_func(request, *args, **kwargs)
    return wrapper

# Create your views here.
@login_required_message
def inicio_gerencia(request):
    search_query = request.GET.get('search')

    if not search_query:
        categorias = Categoria.objects.all()
    else:
        categorias = Categoria.objects.filter(Q(nome__icontains=search_query))

    categorias = categorias.order_by('nome')
    
    paginator = Paginator(categorias, 5)
    page = request.GET.get('page', 1)
    categorias_paginadas = paginator.page(page)

    contexto = {
        'categorias': categorias_paginadas,
        'search_query': search_query,
        'page_obj': categorias_paginadas,
    }
    
    return render(request, 'categoria/index.html', contexto)

@login_required_message
def editar_categoria(request, id):
    categoria = Categoria.objects.get(id=id)
    if request.method == 'POST':
        form = CategoriaForm(request.POST, instance=categoria)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            if Categoria.objects.filter(nome=nome).exclude(id=id).exists():
                form.add_error('nome', 'A categoria com este nome já existe.')
            else:
                form.save()
                return redirect('gerencia:inicio_gerencia')
    else:
        form = CategoriaForm(instance=categoria)
    
    contexto = {
        'form': form
    }
    return render(request, 'gerencia/cadastro_categoria.html', contexto)

@login_required_message
def remover_categoria(request, id):
    categoria = Categoria.objects.get(id=id)
    if request.method == 'POST':
        categoria.delete()
        return redirect('gerencia:inicio_gerencia')
    
    contexto = {
        'categoria': categoria
    }
    return render(request, 'gerencia/remover_categoria.html', contexto)

@login_required_message
def cadastrar_categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            if Categoria.objects.filter(nome=nome).exists():
                form.add_error('nome', 'A categoria com este nome já existe.')
            else:
                form.save()
                return redirect('gerencia:inicio_gerencia')
    else:
        form = CategoriaForm()
    
    contexto = {
        'form': form
    }
    return render(request, 'gerencia/cadastro_categoria.html', contexto)

@login_required_message
def listagem_noticia(request):
    formularioFiltro = NoticiaFilterForm(request.GET or None)
    
    noticias = Noticia.objects.filter(usuario=request.user)  # Filtra pelo usuário logado

    if formularioFiltro.is_valid():
        if formularioFiltro.cleaned_data['titulo']:
            noticias = noticias.filter(titulo__icontains=formularioFiltro.cleaned_data['titulo'])
        if formularioFiltro.cleaned_data['data_publicacao_inicio']:
            noticias = noticias.filter(data_publicacao__gte=formularioFiltro.cleaned_data['data_publicacao_inicio'])
        if formularioFiltro.cleaned_data['data_publicacao_fim']:
            noticias = noticias.filter(data_publicacao__lte=formularioFiltro.cleaned_data['data_publicacao_fim'])
        if formularioFiltro.cleaned_data['categoria']:
            noticias = noticias.filter(categoria=formularioFiltro.cleaned_data['categoria'])
    
    contexto = {
        'noticias': noticias,
        'formularioFiltro': formularioFiltro
    }
    return render(request, 'gerencia/listagem_noticia.html',contexto)

@login_required_message
def cadastrar_noticia(request):
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES)
        if form.is_valid():
            noticia = form.save(commit=False)  # Cria instância sem salvar
            noticia.usuario = request.user  # Atribui o autor (usuário logado)
            noticia.save()  # Salva a notícia no banco
            return redirect('gerencia:listagem_noticia')  # Redireciona para página de sucesso
    else:
        form = NoticiaForm() 

    contexto = {'form': form}
    return render(request, 'gerencia/cadastro_noticia.html', contexto)

@login_required_message
def editar_noticia(request, id):
    noticia = Noticia.objects.get(id=id)
    if request.method == 'POST':
        form = NoticiaForm(request.POST, request.FILES, instance=noticia)
        if form.is_valid():
            noticia_editada = form.save(commit=False)  # Não salva ainda
            noticia_editada.usuario = request.user 
            noticia_editada.save()  # Salva com o usuário intacto
            return redirect('gerencia:listagem_noticia')
    else:
        form = NoticiaForm(instance=noticia)
    
    contexto = {
        'form': form
    }
    return render(request, 'gerencia/cadastro_noticia.html',contexto)

def index(request):
    categoria_nome = request.GET.get('categoria')  # Obtém o parâmetro 'categoria' da URL
    search_query = request.GET.get('search')  # Obtém o parâmetro de busca

    # Filtra as notícias com base na categoria ou na busca
    noticias = Noticia.objects.all()
    if categoria_nome:
        categoria = Categoria.objects.filter(nome=categoria_nome).first()
        if categoria:
            noticias = noticias.filter(categoria=categoria)

    if search_query:
        noticias = noticias.filter(titulo__icontains=search_query)  # Filtra por título, ignorando maiúsculas/minúsculas

    categorias = Categoria.objects.all()  # Pega todas as categorias para exibir no template

    contexto = {
        'noticias': noticias,
        'categorias': categorias,
        'categoria_selecionada': categoria_nome,
        'search_query': search_query,
    }
    return render(request, 'gerencia/index.html', contexto)

gerencia/templates/categoria/index.html
{% extends 'base.html' %}
{% block parte_central %}
<div class="row">
    <!-- Blog entries-->
    <div class="col-lg-4">
        <!-- Search widget-->
        <div class="card mb-4">
            <div class="card-header">Search</div>
            <div class="card-body">
                <form method="get" action=".">
                    <div class="input-group">
                        <input 
                            class="form-control" 
                            type="text" 
                            name="search" 
                            placeholder="Enter search term..." 
                            aria-label="Enter search term..." 
                            aria-describedby="button-search" 
                            value="{{ search_query|default:'' }}"  
                        />
                        <button class="btn btn-primary" id="button-search" type="submit">Go!</button>
                        <a href="{% url 'gerencia:inicio_gerencia' %}" class="btn btn-secondary ms-2">Clear</a>
                    </div>
                </form>
            </div>
        </div>
        <!-- Categories widget-->
        <div class="card mb-4">
            <div class="card-header">
                Categories
                <a href="{% url 'gerencia:cadastro_categoria' %}" class="btn btn-sm btn-primary float-end">Add Category</a>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class="list-unstyled mb-0">
                            {% for categoria in categorias %}
                                <li class="d-flex justify-content-between align-items-center mb-2">
                                    <a href="?categoria={{ categoria.nome }}" class="text-decoration-none">
                                        {{ categoria.nome }}
                                    </a>
                                    <div>
                                        <a href="{% url 'gerencia:editar_categoria' categoria.id %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a href="{% url 'gerencia:remover_categoria' categoria.id %}" class="btn btn-sm btn-outline-danger">Remove</a>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                        <div class="mt-4">
                            {% include 'components/pagination.html' with page_obj=page_obj %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}